import {
  ChatIcon,
  FireIcon,
  HeartIcon,
} from "@/Icons";

export const BASEURL = ""

export const TON_WALLET = 'UQBLN3autdCTC8OJJM3yBEqnCaH0nTHRiskTziPWuYD1x_Ww'
    
export const getlookingfor = (t) => [
    {
      id: "1",
      title: t("Heretodate"),
      description: t("IwanttogoondatesandhaveagoodtimeNolabels"),
      color: "success" // Valid color
    },
    {
      id: "2",
      title: t("Opentochat"),
      description: t("ImheretochatandseewhereitgoesNopressure"),
      color: "warning" // Valid color
    },
    {
      id: "3",
      title: t("Readyforarelationship"),
      description: t("ImlookingforsomethingthatlastsNogames"),
      color: "danger" // Valid color
    },
];

export const getRealationStatus = (t) => [
    { key: "1", label: t("Single") },
    { key: "2", label: t("Taken") },
    { key: "3", label: t("open") },
    { key: "4", label: t("Irathernotsay") },
  ];

export const getlanguages = (t) => [
    { key: "en", label: t("en") },
    { key: "zh", label: t("zh") },
    { key: "es", label: t("es") },
    { key: "hi", label: t("hi") },
    { key: "ar", label: t("ar") },
    { key: "bn", label: t("bn") },
    { key: "fr", label: t("fr") },
    { key: "ru", label: t("ru") },
    { key: "pt", label: t("pt") },
    { key: "id", label: t("id") },
    { key: "ja", label: t("ja") },
    { key: "de", label: t("de") },
    { key: "pa", label: t("pa") },
    { key: "ur", label: t("ur") },
    { key: "ko", label: t("ko") },
    { key: "vi", label: t("vi") },
    { key: "fa", label: t("fa") },
    { key: "tr", label: t("tr") },
    { key: "ta", label: t("ta") },
    { key: "it", label: t("it") },
  ];
 
export const getSexualityStatus = (t) => [
    { key: "1", label: t("straight") },
    { key: "2", label: t("gay") },
    { key: "3", label: t("lesbian") },
    { key: "4", label: t("bisexual") },
    { key: "5", label: t("asexual") },
    { key: "6", label: t("pansexual") },
    { key: "7", label: t("queer") },
    { key: "8", label: t("questioning") },
    { key: "9", label: t("Irathernotsay") },

  ];

export const gethobbies = (t) => [
  { id: 1, name: t("Hiking"), emoji: "🥾" },
  { id: 2, name: t("Cooking"), emoji: "👨‍🍳" },
  { id: 3, name: t("Traveling"), emoji: "✈️" },
  { id: 4, name: t("Guitar"), emoji: "🎸" },
  { id: 5, name: t("Photography"), emoji: "📷" },
  { id: 6, name: t("Yoga"), emoji: "🧘" },
  { id: 7, name: t("Painting"), emoji: "🎨" },
  { id: 8, name: t("Reading"), emoji: "📖" },
  { id: 9, name: t("Running"), emoji: "🏃" },
  { id: 10, name: t("Meditation"), emoji: "🧘‍♂️" },
  { id: 11, name: t("Cycling"), emoji: "🚴" },
  { id: 12, name: t("Surfing"), emoji: "🏄" },
  { id: 13, name: t("Gardening"), emoji: "🌱" },
  { id: 14, name: t("Fishing"), emoji: "🎣" },
  { id: 15, name: t("Rock Climbing"), emoji: "🧗" },
  { id: 16, name: t("Dancing"), emoji: "💃" },
  { id: 17, name: t("Gaming"), emoji: "🎮" },
  { id: 18, name: t("Blogging"), emoji: "📝" },
  { id: 19, name: t("Swimming"), emoji: "🏊" },
  { id: 20, name: t("Martial Arts"), emoji: "🥋" },
  { id: 21, name: t("Bird Watching"), emoji: "🐦" },
  { id: 22, name: t("Karaoke"), emoji: "🎤" },
  { id: 23, name: t("Skateboarding"), emoji: "🛹" },
  { id: 24, name: t("Board Games"), emoji: "🎲" },
  { id: 25, name: t("Archery"), emoji: "🏹" },
  { id: 26, name: t("Skydiving"), emoji: "🪂" },
  { id: 27, name: t("Scuba Diving"), emoji: "🤿" },
  { id: 28, name: t("Tennis"), emoji: "🎾" },
  { id: 29, name: t("Soccer"), emoji: "⚽" },
  { id: 30, name: t("Basketball"), emoji: "🏀" },
  { id: 31, name: t("Golf"), emoji: "🏌️" },
  { id: 32, name: t("Skiing"), emoji: "🎿" },
  { id: 33, name: t("Snowboarding"), emoji: "🏂" },
  { id: 34, name: t("Bowling"), emoji: "🎳" },
  { id: 35, name: t("Wine Tasting"), emoji: "🍷" },
  { id: 36, name: t("Baking"), emoji: "🧁" },
  { id: 37, name: t("Knitting"), emoji: "🧶" },
  { id: 38, name: t("Sewing"), emoji: "🪡" },
  { id: 39, name: t("Pottery"), emoji: "🏺" },
  { id: 40, name: t("Astronomy"), emoji: "🔭" },
  { id: 41, name: t("Camping"), emoji: "🏕️" },
  { id: 42, name: t("Woodworking"), emoji: "🪚" },
  { id: 43, name: t("Volunteering"), emoji: "🤝" },
  { id: 44, name: t("Writing"), emoji: "✍️" },
  { id: 45, name: t("Poetry"), emoji: "📝" },
  { id: 46, name: t("Journaling"), emoji: "📓" },
  { id: 47, name: t("Calligraphy"), emoji: "✒️" },
  { id: 48, name: t("Magic Tricks"), emoji: "🎩" },
  { id: 49, name: t("Stand-up Comedy"), emoji: "🎙️" },
  { id: 50, name: t("Cosplay"), emoji: "🧝" },
  { id: 51, name: t("Tattoo Design"), emoji: "🖋️" },
  { id: 52, name: t("Origami"), emoji: "🦢" },
  { id: 53, name: t("Chess"), emoji: "♟️" },
  { id: 54, name: t("Vegan Cooking"), emoji: "🥗" },
  { id: 55, name: t("Collecting Antiques"), emoji: "🏺" },
  { id: 56, name: t("Fencing"), emoji: "🤺" },
  { id: 57, name: t("Parkour"), emoji: "🤸" },
  { id: 58, name: t("Beekeeping"), emoji: "🐝" },
  { id: 59, name: t("Leather Crafting"), emoji: "🪡" },
  { id: 60, name: t("Mixology"), emoji: "🍸" },
  { id: 61, name: t("Ice Skating"), emoji: "⛸️" },
  { id: 62, name: t("Puzzles"), emoji: "🧩" },
  { id: 63, name: t("Robotics"), emoji: "🤖" },
  { id: 64, name: t("Virtual Reality"), emoji: "🕶️" },
  { id: 65, name: t("Home Brewing"), emoji: "🍺" },
  { id: 66, name: t("Carpentry"), emoji: "🪚" },
  { id: 67, name: t("Flower Arranging"), emoji: "💐" },
  { id: 68, name: t("Metalworking"), emoji: "⚒️" },
  { id: 69, name: t("Jewelry Making"), emoji: "💍" },
  { id: 70, name: t("Animal Rescue"), emoji: "🐾" },
  { id: 71, name: t("Pilates"), emoji: "🤸‍♀️" },
  { id: 72, name: t("Kayaking"), emoji: "🛶" },
  { id: 73, name: t("Bungee Jumping"), emoji: "🪂" },
  { id: 74, name: t("Running Marathons"), emoji: "🏃‍♂️" },
  { id: 75, name: t("Dog Training"), emoji: "🐕" },
  { id: 76, name: t("Horseback Riding"), emoji: "🐎" },
  { id: 77, name: t("Sailing"), emoji: "⛵" },
  { id: 78, name: t("Stand-up Paddleboarding"), emoji: "🏄‍♂️" },
  { id: 79, name: t("Weightlifting"), emoji: "🏋️" },
  { id: 80, name: t("Bodybuilding"), emoji: "💪" },
  { id: 81, name: t("Competitive Gaming"), emoji: "🕹️" },
  { id: 82, name: t("Podcasting"), emoji: "🎧" },
  { id: 83, name: t("Vlogging"), emoji: "📹" },
  { id: 84, name: t("Street Art"), emoji: "🎨" },
  { id: 85, name: t("Historical Reenactments"), emoji: "🏰" },
  { id: 86, name: t("Geocaching"), emoji: "🧭" },
  { id: 87, name: t("Hiking with Dogs"), emoji: "🥾🐶" },
  { id: 88, name: t("DIY Projects"), emoji: "🛠️" },
  { id: 89, name: t("Car Restoration"), emoji: "🚗" },
  { id: 90, name: t("Motorcycling"), emoji: "🏍️" },
  { id: 91, name: t("4x4 Off-roading"), emoji: "🚙" },
  { id: 92, name: t("Mountain Biking"), emoji: "🚵" },
  { id: 93, name: t("Frisbee Golf"), emoji: "🥏" },
  { id: 94, name: t("LARPing"), emoji: "🧙" },
  { id: 95, name: t("Drone Racing"), emoji: "🛸" },
  { id: 96, name: t("Rollerblading"), emoji: "🛼" },
  { id: 97, name: t("Escape Rooms"), emoji: "🗝️" },
  { id: 98, name: t("Trivia Nights"), emoji: "❓" },
  { id: 99, name: t("Kite Surfing"), emoji: "🏄‍♀️" },
  { id: 100, name: t("Astronaut Training"), emoji: "👨‍🚀" }
];


  export const getPetStatus = (t) => [
    { key: "1", label: t("has_pets") },
    { key: "2", label: t("no_pets") },
    { key: "3", label: t("likes_pets") },
    { key: "4", label: t("does_not_like_pets") },
    { key: "5", label: t("Irathernotsay") },

  ];

  export const getDrinkStatus =(t) => [
    { key: "1", label: t("drinks_regularly") },
    { key: "2", label: t("occasionally_drinks") },
    { key: "3", label: t("does_not_drink") },
    { key: "4", label: t("trying_to_quit_drinking") },
    { key: "5", label: t("Irathernotsay") },

  ];

  export const getSmokingStatus =(t) => [
    { key: "1", label: t("smokes_regularly") },
    { key: "2", label: t("occasionally_smokes") },
    { key: "3", label: t("does_not_smoke") },
    { key: "4", label: t("trying_to_quit_smoking") },
    { key: "5", label: t("Irathernotsay") },

  ];

  export const getKidStatus =(t) => [
    { key: "1", label: t("has_kids") },
    { key: "2", label: t("no_kids") },
    { key: "3", label: t("wants_kids") },
    { key: "4", label: t("does_not_want_kids") },
    { key: "5", label: t("open_to_kids") },
    { key: "6", label: t("Irathernotsay") },

  ];

export const getStaticData = (t: (key: string) => string) => ({
  Items: [
    {
      id: "1",
      title: t("Heretodate"),
      description: t("IwanttogoondatesandhaveagoodtimeNolabels"),
      icon: FireIcon,
      color: "success"
    },
    {
      id: "2",
      title: t("Opentochat"),
      description: t("ImheretochatandseewhereitgoesNopressure"),
      icon: ChatIcon ,
      color: "warning"
    },
    {
      id: "3",
      title: t("Readyforarelationship"),
      description: t("ImlookingforsomethingthatlastsNogames"),
      icon: HeartIcon ,
      color: "danger"
    }
  ],
  RealationStatus: getRealationStatus(t),
  languages: getlanguages(t),
  SexualityStatus: getSexualityStatus(t),
  hobbies: gethobbies(t),
  PetStatus: getPetStatus(t),
  DrinkStatus: getDrinkStatus(t),
  SmokingStatus: getSmokingStatus(t),
  KidStatus: getKidStatus(t),
});


export const getEducationStatus = (t) => [
  { key: "high_school", label: t("high_school") },
  { key: "some_college", label: t("some_college") },
  { key: "bachelor_degree", label: t("bachelor_degree") },
  { key: "master_degree", label: t("master_degree") },
  { key: "phd", label: t("phd") },
  { key: "prefer_not_to_say", label: t("prefer_not_to_say") },
];


export const countries = [
  { key: "AF", name: "Afghanistan", flag: "🇦🇫" },
  { key: "AL", name: "Albania", flag: "🇦🇱" },
  { key: "DZ", name: "Algeria", flag: "🇩🇿" },
  { key: "AS", name: "American Samoa", flag: "🇦🇸" },
  { key: "AD", name: "Andorra", flag: "🇦🇩" },
  { key: "AO", name: "Angola", flag: "🇦🇴" },
  { key: "AI", name: "Anguilla", flag: "🇦🇮" },
  { key: "AQ", name: "Antarctica", flag: "🇦🇶" },
  { key: "AR", name: "Argentina", flag: "🇦🇷" },
  { key: "AM", name: "Armenia", flag: "🇦🇲" },
  { key: "AW", name: "Aruba", flag: "🇦🇼" },
  { key: "AU", name: "Australia", flag: "🇦🇺" },
  { key: "AT", name: "Austria", flag: "🇦🇹" },
  { key: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
  { key: "BS", name: "Bahamas", flag: "🇧🇸" },
  { key: "BH", name: "Bahrain", flag: "🇧🇭" },
  { key: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { key: "BB", name: "Barbados", flag: "🇧🇧" },
  { key: "BY", name: "Belarus", flag: "🇧🇾" },
  { key: "BE", name: "Belgium", flag: "🇧🇪" },
  { key: "BZ", name: "Belize", flag: "🇧🇿" },
  { key: "BJ", name: "Benin", flag: "🇧🇯" },
  { key: "BM", name: "Bermuda", flag: "🇧🇲" },
  { key: "BT", name: "Bhutan", flag: "🇧🇹" },
  { key: "BO", name: "Bolivia", flag: "🇧🇴" },
  { key: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { key: "BW", name: "Botswana", flag: "🇧🇼" },
  { key: "BR", name: "Brazil", flag: "🇧🇷" },
  { key: "IO", name: "British Indian Ocean Territory", flag: "🇮🇴" },
  { key: "VG", name: "British Virgin Islands", flag: "🇻🇬" },
  { key: "BN", name: "Brunei", flag: "🇧🇳" },
  { key: "BG", name: "Bulgaria", flag: "🇧🇬" },
  { key: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { key: "BI", name: "Burundi", flag: "🇧🇮" },
  { key: "KH", name: "Cambodia", flag: "🇰🇭" },
  { key: "CM", name: "Cameroon", flag: "🇨🇲" },
  { key: "CA", name: "Canada", flag: "🇨🇦" },
  { key: "CV", name: "Cape Verde", flag: "🇨🇻" },
  { key: "KY", name: "Cayman Islands", flag: "🇰🇾" },
  { key: "CF", name: "Central African Republic", flag: "🇨🇫" },
  { key: "TD", name: "Chad", flag: "🇹🇩" },
  { key: "CL", name: "Chile", flag: "🇨🇱" },
  { key: "CN", name: "China", flag: "🇨🇳" },
  { key: "CX", name: "Christmas Island", flag: "🇨🇽" },
  { key: "CC", name: "Cocos (Keeling) Islands", flag: "🇨🇨" },
  { key: "CO", name: "Colombia", flag: "🇨🇴" },
  { key: "KM", name: "Comoros", flag: "🇰🇲" },
  { key: "CG", name: "Congo", flag: "🇨🇬" },
  { key: "CD", name: "Congo (DRC)", flag: "🇨🇩" },
  { key: "CK", name: "Cook Islands", flag: "🇨🇰" },
  { key: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { key: "HR", name: "Croatia", flag: "🇭🇷" },
  { key: "CU", name: "Cuba", flag: "🇨🇺" },
  { key: "CY", name: "Cyprus", flag: "🇨🇾" },
  { key: "CZ", name: "Czech Republic", flag: "🇨🇿" },
  { key: "DK", name: "Denmark", flag: "🇩🇰" },
  { key: "DJ", name: "Djibouti", flag: "🇩🇯" },
  { key: "DM", name: "Dominica", flag: "🇩🇲" },
  { key: "DO", name: "Dominican Republic", flag: "🇩🇴" },
  { key: "EC", name: "Ecuador", flag: "🇪🇨" },
  { key: "EG", name: "Egypt", flag: "🇪🇬" },
  { key: "SV", name: "El Salvador", flag: "🇸🇻" },
  { key: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
  { key: "ER", name: "Eritrea", flag: "🇪🇷" },
  { key: "EE", name: "Estonia", flag: "🇪🇪" },
  { key: "ET", name: "Ethiopia", flag: "🇪🇹" },
  { key: "FK", name: "Falkland Islands", flag: "🇫🇰" },
  { key: "FO", name: "Faroe Islands", flag: "🇫🇴" },
  { key: "FJ", name: "Fiji", flag: "🇫🇯" },
  { key: "FI", name: "Finland", flag: "🇫🇮" },
  { key: "FR", name: "France", flag: "🇫🇷" },
  { key: "GF", name: "French Guiana", flag: "🇬🇫" },
  { key: "PF", name: "French Polynesia", flag: "🇵🇫" },
  { key: "TF", name: "French Southern Territories", flag: "🇹🇫" },
  { key: "GA", name: "Gabon", flag: "🇬🇦" },
  { key: "GM", name: "Gambia", flag: "🇬🇲" },
  { key: "GE", name: "Georgia", flag: "🇬🇪" },
  { key: "DE", name: "Germany", flag: "🇩🇪" },
  { key: "GH", name: "Ghana", flag: "🇬🇭" },
  { key: "GI", name: "Gibraltar", flag: "🇬🇮" },
  { key: "GR", name: "Greece", flag: "🇬🇷" },
  { key: "GL", name: "Greenland", flag: "🇬🇱" },
  { key: "GD", name: "Grenada", flag: "🇬🇩" },
  { key: "GU", name: "Guam", flag: "🇬🇺" },
  { key: "GT", name: "Guatemala", flag: "🇬🇹" },
  { key: "GG", name: "Guernsey", flag: "🇬🇬" },
  { key: "GN", name: "Guinea", flag: "🇬🇳" },
  { key: "GW", name: "Guinea-Bissau", flag: "🇬🇼" },
  { key: "GY", name: "Guyana", flag: "🇬🇾" },
  { key: "HT", name: "Haiti", flag: "🇭🇹" },
  { key: "HN", name: "Honduras", flag: "🇭🇳" },
  { key: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { key: "HU", name: "Hungary", flag: "🇭🇺" },
  { key: "IS", name: "Iceland", flag: "🇮🇸" },
  { key: "IN", name: "India", flag: "🇮🇳" },
  { key: "ID", name: "Indonesia", flag: "🇮🇩" },
  { key: "IR", name: "Iran", flag: "🇮🇷" },
  { key: "IQ", name: "Iraq", flag: "🇮🇶" },
  { key: "IE", name: "Ireland", flag: "🇮🇪" },
  { key: "IL", name: "Israel", flag: "🇮🇱" },
  { key: "IT", name: "Italy", flag: "🇮🇹" },
  { key: "JM", name: "Jamaica", flag: "🇯🇲" },
  { key: "JP", name: "Japan", flag: "🇯🇵" },
  { key: "JE", name: "Jersey", flag: "🇯🇪" },
  { key: "JO", name: "Jordan", flag: "🇯🇴" },
  { key: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { key: "KE", name: "Kenya", flag: "🇰🇪" },
  { key: "KI", name: "Kiribati", flag: "🇰🇮" },
  { key: "KR", name: "South Korea", flag: "🇰🇷" },
  { key: "KW", name: "Kuwait", flag: "🇰🇼" },
  { key: "KG", name: "Kyrgyzstan", flag: "🇰🇬" },
  { key: "LA", name: "Laos", flag: "🇱🇦" },
  { key: "LV", name: "Latvia", flag: "🇱🇻" },
  { key: "LB", name: "Lebanon", flag: "🇱🇧" },
  { key: "LS", name: "Lesotho", flag: "🇱🇸" },
  { key: "LR", name: "Liberia", flag: "🇱🇷" },
  { key: "LY", name: "Libya", flag: "🇱🇾" },
  { key: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  { key: "LT", name: "Lithuania", flag: "🇱🇹" },
  { key: "LU", name: "Luxembourg", flag: "🇱🇺" },
  { key: "MO", name: "Macau", flag: "🇲🇴" },
  { key: "MK", name: "North Macedonia", flag: "🇲🇰" },
  { key: "MG", name: "Madagascar", flag: "🇲🇬" },
  { key: "MW", name: "Malawi", flag: "🇲🇼" },
  { key: "MY", name: "Malaysia", flag: "🇲🇾" },
  { key: "MV", name: "Maldives", flag: "🇲🇻" },
  { key: "ML", name: "Mali", flag: "🇲🇱" },
  { key: "MT", name: "Malta", flag: "🇲🇹" },
  { key: "MH", name: "Marshall Islands", flag: "🇲🇭" },
  { key: "MQ", name: "Martinique", flag: "🇲🇶" },
  { key: "MR", name: "Mauritania", flag: "🇲🇷" },
  { key: "MU", name: "Mauritius", flag: "🇲🇺" },
  { key: "YT", name: "Mayotte", flag: "🇾🇹" },
  { key: "MX", name: "Mexico", flag: "🇲🇽" },
  { key: "FM", name: "Micronesia", flag: "🇫🇲" },
  { key: "MD", name: "Moldova", flag: "🇲🇩" },
  { key: "MC", name: "Monaco", flag: "🇲🇨" },
  { key: "MN", name: "Mongolia", flag: "🇲🇳" },
  { key: "ME", name: "Montenegro", flag: "🇲🇪" },
  { key: "MS", name: "Montserrat", flag: "🇲🇸" },
  { key: "MA", name: "Morocco", flag: "🇲🇦" },
  { key: "MZ", name: "Mozambique", flag: "🇲🇿" },
  { key: "MM", name: "Myanmar", flag: "🇲🇲" },
  { key: "NA", name: "Namibia", flag: "🇳🇦" },
  { key: "NR", name: "Nauru", flag: "🇳🇷" },
  { key: "NP", name: "Nepal", flag: "🇳🇵" },
  { key: "NL", name: "Netherlands", flag: "🇳🇱" },
  { key: "NC", name: "New Caledonia", flag: "🇳🇨" },
  { key: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { key: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { key: "NE", name: "Niger", flag: "🇳🇪" },
  { key: "NG", name: "Nigeria", flag: "🇳🇬" },
  { key: "NU", name: "Niue", flag: "🇳🇺" },
  { key: "NF", name: "Norfolk Island", flag: "🇳🇫" },
  { key: "KP", name: "North Korea", flag: "🇰🇵" },
  { key: "NO", name: "Norway", flag: "🇳🇴" },
  { key: "OM", name: "Oman", flag: "🇴🇲" },
  { key: "PK", name: "Pakistan", flag: "🇵🇰" },
  { key: "PW", name: "Palau", flag: "🇵🇼" },
  { key: "PA", name: "Panama", flag: "🇵🇦" },
  { key: "PG", name: "Papua New Guinea", flag: "🇵🇬" },
  { key: "PY", name: "Paraguay", flag: "🇵🇾" },
  { key: "PE", name: "Peru", flag: "🇵🇪" },
  { key: "PH", name: "Philippines", flag: "🇵🇭" },
  { key: "PL", name: "Poland", flag: "🇵🇱" },
  { key: "PT", name: "Portugal", flag: "🇵🇹" },
  { key: "PR", name: "Puerto Rico", flag: "🇵🇷" },
  { key: "QA", name: "Qatar", flag: "🇶🇦" },
  { key: "RE", name: "Réunion", flag: "🇷🇪" },
  { key: "RO", name: "Romania", flag: "🇷🇴" },
  { key: "RU", name: "Russia", flag: "🇷🇺" },
  { key: "RW", name: "Rwanda", flag: "🇷🇼" },
  { key: "BL", name: "Saint Barthélemy", flag: "🇧🇱" },
  { key: "SH", name: "Saint Helena", flag: "🇸🇭" },
  { key: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { key: "LC", name: "Saint Lucia", flag: "🇱🇨" },
  { key: "MF", name: "Saint Martin", flag: "🇲🇫" },
  { key: "PM", name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  { key: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { key: "WS", name: "Samoa", flag: "🇼🇸" },
  { key: "SM", name: "San Marino", flag: "🇸🇲" },
  { key: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹" },
  { key: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { key: "SN", name: "Senegal", flag: "🇸🇳" },
  { key: "RS", name: "Serbia", flag: "🇷🇸" },
  { key: "SC", name: "Seychelles", flag: "🇸🇨" },
  { key: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  { key: "SG", name: "Singapore", flag: "🇸🇬" },
  { key: "SX", name: "Sint Maarten", flag: "🇸🇽" },
  { key: "SK", name: "Slovakia", flag: "🇸🇰" },
  { key: "SI", name: "Slovenia", flag: "🇸🇮" },
  { key: "SB", name: "Solomon Islands", flag: "🇸🇧" },
  { key: "SO", name: "Somalia", flag: "🇸🇴" },
  { key: "ZA", name: "South Africa", flag: "🇿🇦" },
  { key: "GS", name: "South Georgia and the South Sandwich Islands", flag: "🇬🇸" },
  { key: "ES", name: "Spain", flag: "🇪🇸" },
  { key: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { key: "SD", name: "Sudan", flag: "🇸🇩" },
  { key: "SR", name: "Suriname", flag: "🇸🇷" },
  { key: "SJ", name: "Svalbard and Jan Mayen", flag: "🇸🇯" },
  { key: "SE", name: "Sweden", flag: "🇸🇪" },
  { key: "CH", name: "Switzerland", flag: "🇨🇭" },
  { key: "SY", name: "Syria", flag: "🇸🇾" },
  { key: "TW", name: "Taiwan", flag: "🇹🇼" },
  { key: "TJ", name: "Tajikistan", flag: "🇹🇯" },
  { key: "TZ", name: "Tanzania", flag: "🇹🇿" },
  { key: "TH", name: "Thailand", flag: "🇹🇭" },
  { key: "TL", name: "Timor-Leste", flag: "🇹🇱" },
  { key: "TG", name: "Togo", flag: "🇹🇬" },
  { key: "TK", name: "Tokelau", flag: "🇹🇰" },
  { key: "TO", name: "Tonga", flag: "🇹🇴" },
  { key: "TT", name: "Trinidad and Tobago", flag: "🇹🇹" },
  { key: "TN", name: "Tunisia", flag: "🇹🇳" },
  { key: "TR", name: "Turkey", flag: "🇹🇷" },
  { key: "TM", name: "Turkmenistan", flag: "🇹🇲" },
  { key: "TC", name: "Turks and Caicos Islands", flag: "🇹🇨" },
  { key: "TV", name: "Tuvalu", flag: "🇹🇻" },
  { key: "UG", name: "Uganda", flag: "🇺🇬" },
  { key: "UA", name: "Ukraine", flag: "🇺🇦" },
  { key: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { key: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { key: "US", name: "United States", flag: "🇺🇸" },
  { key: "UY", name: "Uruguay", flag: "🇺🇾" },
  { key: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
  { key: "VU", name: "Vanuatu", flag: "🇻🇺" },
  { key: "VE", name: "Venezuela", flag: "🇻🇪" },
  { key: "VN", name: "Vietnam", flag: "🇻🇳" },
  { key: "WF", name: "Wallis and Futuna", flag: "🇼🇫" },
  { key: "EH", name: "Western Sahara", flag: "🇪🇭" },
  { key: "YE", name: "Yemen", flag: "🇾🇪" },
  { key: "ZM", name: "Zambia", flag: "🇿🇲" },
  { key: "ZW", name: "Zimbabwe", flag: "🇿🇼" }
]; 
